In [65]:
# Import Dependencies
import pandas as pd
from pandas import DataFrame
import numpy as np
import sqlalchemy
from sqlalchemy import create_engine, MetaData, inspect
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Numeric, Text, Float
from sqlalchemy.sql import text
from sqlalchemy.orm import Session
from sqlalchemy.ext.automap import automap_base
from flask import Flask, jsonify, render_template, request, redirect
import json

In [47]:
# Create an engine for the database and connect
engine = create_engine("sqlite:///data.sqlite", echo=False)
engine.connect()

In [48]:
#Inspect table names
inspector = inspect(engine)
inspector.get_table_names()

['DPI', 'FPSR', 'PCE']

In [49]:
# Reflect Database into ORM classes
Base = automap_base()
Base.prepare(engine,reflect=True)
Base.classes.keys()

[]

In [50]:
# Create a reference to each table
class DPI(Base):
    __tablename__ = "DPI"
    __table_args__ = {"extend_existing":True}
    field1 = Column(Text,primary_key=True)

class FPSR(Base):
    __tablename__ = "FPSR"
    __table_args__ = {"extend_existing":True}
    DATE = Column(Text,primary_key=True)

class PCE(Base):
    __tablename__ = "PCE"
    __table_args__ = {"extend_existing":True}
    GeoName = Column(Text,primary_key=True)
    Line = Column(Text,primary_key=True)

Base.prepare()
session = Session(engine)
app = Flask(__name__)

In [62]:
GeoName_List = [r.GeoName for r in session.query(PCE.GeoName).distinct()]
GeoName_List

['United States',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming',
 'New England',
 'Mideast',
 'Great Lakes',
 'Plains',
 'Southeast',
 'Southwest',
 'Rocky Mountain',
 'Far West']

In [63]:
Description_List = [r.Description for r in session.query(PCE.Description).distinct()]
Description_List

['Personal consumption expenditures',
 'Goods',
 'Durable goods',
 'Motor vehicles and parts',
 'Furnishings and durable household equipment',
 'Recreational goods and vehicles',
 'Other durable goods',
 'Nondurable goods',
 'Food and beverages purchased for off-premises consumption',
 'Clothing and footwear',
 'Gasoline and other energy goods',
 'Other nondurable goods',
 'Services',
 'Household consumption expenditures (for services)',
 'Housing and utilities',
 'Health care',
 'Transportation services',
 'Recreation services',
 'Food services and accommodations',
 'Financial services and insurance',
 'Other services',
 'Final consumption expenditures of nonprofit institutions serving households (NPISHs)',
 'Gross output of nonprofit institutions',
 'Less: Receipts from sales of goods and services by nonprofit institutions']

In [64]:
Component_Name = [r.ComponentName for r in session.query(PCE.ComponentName).distinct()]
Component_Name

['Total personal consumption expenditures (PCE) by state (millions of dollars)']

In [68]:
sql = "select * from PCE"
df = pd.read_sql(sql, engine)
df.head(10)

,GeoFIPS,GeoName,Region,ComponentId,ComponentName,Line,IndustryClassification,Description,1997,1998,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,0,United States,,1,Total personal consumption expenditures (PCE) ...,1,...,Personal consumption expenditures,5557762,5899792,...,9745473,10008303,9840449,10196850,10682155,11044056,11355529,11858228,12327828,12816386
1,0,United States,,1,Total personal consumption expenditures (PCE) ...,2,...,Goods,2003806,2105478,...,3356541,3370357,3191925,3357470,3589317,3732508,3828877,3965012,4028728,4117111
2,0,United States,,1,Total personal consumption expenditures (PCE) ...,3,...,Durable goods,715530,779295,...,1184633,1102283,1023319,1070692,1125327,1191860,1241693,1296383,1367137,1411006
3,0,United States,,1,Total personal consumption expenditures (PCE) ...,4,...,Motor vehicles and parts,293083,320205,...,400573,339630,317058,341955,363458,395763,416132,441874,472169,480792
4,0,United States,,1,Total personal consumption expenditures (PCE) ...,5,...,Furnishings and durable household equipment,160491,173579,...,283458,268714,244311,250417,260672,271383,281557,294270,311516,325154
5,0,United States,,1,Total personal consumption expenditures (PCE) ...,6,...,Recreational goods and vehicles,174632,191360,...,335780,329331,303775,312735,320981,336605,348100,357404,372392,385474
6,0,United States,,1,Total personal consumption expenditures (PCE) ...,7,...,Other durable goods,87324,94151,...,164822,164608,158175,165585,180216,188109,195904,202835,211060,219586
7,0,United States,,1,Total personal consumption expenditures (PCE) ...,8,...,Nondurable goods,1288276,1326183,...,2171908,2268074,2168606,2286778,2463990,2540648,2587184,2668629,2661591,2706105
8,0,United States,,1,Total personal consumption expenditures (PCE) ...,9,...,Food and beverages purchased for off-premises ...,474776,487437,...,737331,772884,769958,788899,829146,848789,857547,884403,898957,915074
9,0,United States,,1,Total personal consumption expenditures (PCE) ...,10,...,Clothing and footwear,247496,257805,...,323692,319506,306498,320558,338946,354287,363625,375954,385461,393654